export const academicTags = [
  "Aeronautics and Astronautics",
  "Anthropology",
  "Architecture",
  "Art",
  "Astronomy",
  "Biochemistry",
  "Biology",
  "Business",
  "Chemistry",
  "Communication",
  "Computer Science",
  "Computer Engineering",
  "Data Science",
  "Design",
  "Economics",
  "Education",
  "Electrical and Computer Engineering",
  "English",
  "Engineering",
  "Environment",
  "Geography",
  "History",
  "Informatics",
  "Law",
  "Linguistics",
  "Literature",
  "Marine Biology",
  "Math",
  "Mechanical Engineering", 
  "Medicine",
  "Music",
  "Neuroscience",
  "Nursing",
  "Oceanography",
  "Philosophy",
  "Political Science",
  "Psychology",
  "Public Health",
  "Sociology",
  "Statistics",
  "UI/UX",
];

export const engineeringTags = [
  // 细分专业：
  "Bioengineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Industrial Engineering",
  "Materials Science & Engineering",
  "HCDE",
];
export const csTags = [
  "Artificial Intelligence",
  "Computer Vision",
  "Data Science",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Software Development",
  "Web Development",
  "Mobile Development",
  "Cloud Computing",
  "Hackathon",
  "Open Source",
  "Cybersecurity",
  "Data Analytics",
  "Game Development",
  "Robotics",
];
export const businessTags = [
  "Accounting",
  "Entrepreneurship",
  "Finance",
  "Information Systems",
  "Marketing",
  "Management", // Human Resources Management, Operations & Supply Chain Management
];

export const dormTags = [
  "Cedar Apartments",
  "Elm Hall",
  "Fraternity",
  "Hansee Hall",
  "Lander Hall",
  "Madrona Hall",
  "Maple Hall",
  "McCarty Hall",
  "McMahon Hall",
  "Mercer Court",
  "Nordheim Court",
  "North Campus",
  "Oak Hall",
  "Oliver Hall",
  "Poplar Hall",
  "Sorority",
  "Spratlen Hall",
  "Stevens Court",
  "Terry Hall",
  "West Campus",
  "Willow Hall",
];

export const sportsTags = [
  "Badminton",
  "Baseball",
  "Basketball",
  "Bowling",
  "Cycling",
  "Football",
  "Golf",
  "Judo",
  "Jujitsu",
  "Martial Arts",
  "Pool",
  "Running",
  "Skateboarding",
  "Skiing",
  "Snowboarding",
  "Soccer",
  "Swimming",
  "Table Tennis",
  "Tennis",
  "Volleyball",
  "Yoga",
];

export const interestTags = [
  "Music", "Drama", "Reading",
  "Writing", "Photography", "Cooking",
  "Hiking", "Gaming", "Crafting",
  "Gardening", "Fitness", "Fashion",
];

// 合并所有tag
export const allTags = [
  ...academicTags,
  ...engineeringTags,
  ...csTags,
  ...businessTags,
  ...dormTags,
  ...interestTags,
];
